### ISSUE TITLE
Error during install from npm

### ISSUE THREAD

**Issue by PaulinaGogalinska** [Bajoras/smartclient-lgpl#1]
ERROR! Failed to get SmartClient directory listing from: https://www.smartclient.com/builds/SmartClient/12.1p/LGPL/latest

`
> smartclient-lgpl@0.9.8 install C:\Projects\anon\grails-app\assets\javascripts\node_modules\smartclient-lgpl
> node update.js    false
Install SmartClient 12.1 runtime, build date latest, at C:\Projects\anon\grails-app\assets\javascripts\isomorphic? [yes]: yes
ERROR! Failed to get SmartClient directory listing from: https://www.smartclient.com/builds/SmartClient/12.1p/LGPL/latest
npm WARN javascripts No description
npm WARN javascripts No repository field.
npm WARN javascripts No license field.
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967194
npm ERR! smartclient-lgpl@0.9.8 install: `node update.js    false`
npm ERR! Exit status 4294967194
npm ERR!
npm ERR! Failed at the smartclient-lgpl@0.9.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pk\AppData\Roaming\npm-cache\_logs\2022-04-29T07_59_58_976Z-debug.log
`

**Comment by Bajoras** [comment]
try the latest version 1.0.2

**Comment by Bajoras** [comment]
due to a long time no response I will close the issue. if the problem exists with the newest version open the issue again
